trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Test
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: accuknox-iac@2
      inputs:
        accuknoxEndpoint: '$(accuknox-enpoint)'
        accuknoxToken: '$(accuknox-token)'
        accuknoxLabel: '$(accuknox-label)'
        inputQuiet: true
        inputCompact: true
