# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Test

steps:
    
- task: accuknox-sq-sast@1
  inputs:
    sonarQubeUrl: '$(sonarQubeUrl)'
    sonarQubeToken: '$(sonarQubeToken)'
    sonarQubeProjectKey: '$(sonarQubeProjectKey)'
    accuknoxEndpoint: '$(accuknox-enpoint)'
    accuknoxToken: '$(accuknox-token)'
    accuknoxLabel: '$(accuknox-label)'
    accuknoxTenantId: "123"
    skipSonarQubeScan: true 
    qualityGate: false